### ISSUE TITLE
Feature request: oauth client id/secret via env var

### ISSUE THREAD

**Issue by holzman** [vkuznet/auth-proxy-server#2]
Hi Valentin,

For ease of deployment in a k8s environment, it would be nice if we could override client_id and client_secret from the configuration file - we could then have a public config file and manage only those two items as secrets.

Obviously very low priority.

**Comment by vkuznet** [comment]
Burt, the new release which  implements this is 0.2.12, the image is available on registry.cern.ch/cmsweb/auth-proxy-server:0.2.12 or docker hub as cmssw/auth-proxy-server:0.2.12

What you need is to setup APS_CLIENT_ID and APS_CLIENT_SECRET and aps will read them during initialization.
